/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardRouteImport } from './routes/card'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedActivationRouteImport } from './routes/_authenticated/activation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminCardsRouteImport } from './routes/_authenticated/admin/cards'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin/codes'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin/fees'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin/customers.index'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin/customers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivationRoute = AuthenticatedActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCardsRoute = AuthenticatedAdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/activation': typeof AuthenticatedActivationRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/activation': typeof AuthenticatedActivationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/_authenticated/activation': typeof AuthenticatedActivationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/auth'
    | '/card'
    | '/how-it-works'
    | '/security'
    | '/support'
    | '/activation'
    | '/admin'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/codes'
    | '/admin/fees'
    | '/admin/payments'
    | '/admin/settings'
    | '/api/public/stripe-webhook'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/auth'
    | '/card'
    | '/how-it-works'
    | '/security'
    | '/support'
    | '/activation'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/codes'
    | '/admin/fees'
    | '/admin/payments'
    | '/admin/settings'
    | '/api/public/stripe-webhook'
    | '/admin'
    | '/admin/customers/$id'
    | '/admin/customers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/auth'
    | '/card'
    | '/how-it-works'
    | '/security'
    | '/support'
    | '/_authenticated/activation'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/cards'
    | '/_authenticated/admin/codes'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
  CardRoute: typeof CardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activation': {
      id: '/_authenticated/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof AuthenticatedActivationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cards': {
      id: '/_authenticated/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AuthenticatedAdminCardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCardsRoute: typeof AuthenticatedAdminCardsRoute
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCardsRoute: AuthenticatedAdminCardsRoute,
  AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  AuthenticatedAdminCustomersIndexRoute: AuthenticatedAdminCustomersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivationRoute: typeof AuthenticatedActivationRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivationRoute: AuthenticatedActivationRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
  CardRoute: CardRoute,
  HowItWorksRoute: HowItWorksRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
